/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useMemo, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";

export default function PWScene(props) {
    const { nodes, materials } = useGLTF('/Tree.glb')

    const fillMaterial = useMemo(
        () =>
            new THREE.MeshBasicMaterial({
                color: '#041B22',
            }),
        []
    )

    const outlineMaterial = useMemo(
        () =>
            new THREE.MeshBasicMaterial({
                color: '#082B34',
            }),
        []
    )

    return (
        <group {...props} dispose={null}>
            <group position={[0, -0.536, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane002_1.geometry}
                    material={fillMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane002_2.geometry}
                    material={outlineMaterial}
                />
            </group>
            <group
                position={[0, -0.115, 0]}
                rotation={[-Math.PI, 1.362, -Math.PI]}
                scale={[0.758, 0.874, 0.758]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane003.geometry}
                    material={fillMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane003_1.geometry}
                    material={outlineMaterial}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={fillMaterial}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_1.geometry}
                material={outlineMaterial}
            />
        </group>
    )
}

useGLTF.preload('/Tree.glb')
